name: 'Build docs'
description: 'Builds custom rOpenSci pkgdown site from  a git remote.'
inputs:
  repo_url:
    description: 'URL of the git repository'
    required: true
  subdir:
    description: 'Subdirectory containing the R package'
    required: false
  registry:
    description: 'Name of the registry that owns the package'
    required: false
  deploy_url:
    description: 'deprecated'
    required: false
runs:
  using: 'docker'
  image: 'docker://runiverse/build-docs'
  args:
    - ${{ inputs.repo_url }}
    - ${{ inputs.subdir }}
    - ${{ inputs.registry }}